version = 0.1


[development.deploy.parameters]
stack_name = "ipv-passport-back-development"
s3_bucket = "di-ipv-cri-lambda-artifact-bucket"
s3_prefix = "passport-back-development"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"development\""

