version = 0.1


[dev.deploy.parameters]
stack_name = "ipv-cri-uk-passport-back-development"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ipv-cri-uk-passport-back-development"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""

[integration.deploy.parameters]
stack_name = "ipv-cri-uk-passport-back-integration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ipv-cri-uk-passport-back-integration"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"

