AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ipv-cri-uk-passport-back

Globals:
  Function:
    Timeout: 40

Parameters:
  Environment:
    Type: String

Resources:

  IPVCriUKPassportAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: IPV CRI UK Passport API Gateway
      StageName: !Sub ${Environment}

  IPVDcsCredentialFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-dcs-credential-${Environment}"
      Handler: uk.gov.di.ipv.cri.passport.dcscredential.DcsCredentialHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/dcscredential
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          DCS_RESPONSE_TABLE_NAME: !Select [1, !Split ['/', !GetAtt DCSResponseTable.Arn]]
          CRI_PASSPORT_ACCESS_TOKENS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt CRIPassportAccessTokensTable.Arn]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DCSResponseTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CRIPassportAccessTokensTable
      Events:
        IPVCriUKPassportAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCriUKPassportAPI
            Path: /credential
            Method: GET

  IPVDcsAccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-dcs-token-${Environment}"
      Handler: uk.gov.di.ipv.cri.passport.accesstoken.AccessTokenHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/accesstoken
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          CRI_PASSPORT_AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt CRIPassportAuthCodesTable.Arn]]
          CRI_PASSPORT_ACCESS_TOKENS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt CRIPassportAccessTokensTable.Arn]]
          CREDENTIAL_ISSUERS_CONFIG_PARAM_PREFIX: !Sub "/${Environment}/credentialIssuers/ukPassport/clients"
          PASSPORT_CRI_CLIENT_AUTH_MAX_TTL: "/${Environment}/credentialIssuers/ukPassport/self/maxJwtTtl"
          PASSPORT_CRI_CLIENT_AUDIENCE: "/${Environment}/credentialIssuers/ukPassport/self/audienceForClients"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref CRIPassportAuthCodesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CRIPassportAccessTokensTable
      Events:
        IPVCriUKPassportAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCriUKPassportAPI
            Path: /token
            Method: POST

  IPVPassportFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-passport-${Environment}"
      Handler: uk.gov.di.ipv.cri.passport.passport.PassportHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/passport
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          DCS_RESPONSE_TABLE_NAME: !Select [1, !Split ['/', !GetAtt DCSResponseTable.Arn]]
          CRI_PASSPORT_ACCESS_TOKENS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt CRIPassportAccessTokensTable.Arn]]
          CRI_PASSPORT_AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt CRIPassportAuthCodesTable.Arn]]
          DCS_ENCRYPTION_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/dcs/encryptionCertForPassportToEncrypt"
          DCS_SIGNING_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/dcs/signingCertForPassportToVerify"
          PASSPORT_CRI_SIGNING_KEY_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/self/signingKeyForPassportToSign"
          PASSPORT_CRI_ENCRYPTION_KEY_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/self/encryptionKeyForPassportToDecrypt"
          PASSPORT_CRI_TLS_KEY_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/self/tlsKey"
          PASSPORT_CRI_SIGNING_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/self/signingCertForDcsToVerify"
          PASSPORT_CRI_ENCRYPTION_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/self/encryptionCertForDcsToEncrypt"
          PASSPORT_CRI_TLS_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/self/tlsCert"
          DCS_POST_URL_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/dcs/postUrl"
          DCS_TLS_ROOT_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/dcs/tlsRootCertificate"
          DCS_TLS_INTERMEDIATE_CERT_PARAM: !Sub "/${Environment}/credentialIssuers/ukPassport/dcs/tlsIntermediateCertificate"
          CREDENTIAL_ISSUERS_CONFIG_PARAM_PREFIX: !Sub "/${Environment}/credentialIssuers/ukPassport/clients"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DCSResponseTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CRIPassportAccessTokensTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CRIPassportAuthCodesTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/credentialIssuers/ukPassport/*
      Events:
        IPVCriUKPassportAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCriUKPassportAPI
            Path: /passport
            Method: POST

  JwtVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-jwt-verification-${Environment}"
      Handler: uk.gov.di.ipv.cri.passport.jwtverification.JwtVerificationHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/jwtverification
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          CREDENTIAL_ISSUERS_CONFIG_PARAM_PREFIX: !Sub "/${Environment}/credentialIssuers/ukPassport/clients"
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub "${Environment}/credentialIssuers/ukPassport/clients/*"
      Events:
        IPVCriUKPassportAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCriUKPassportAPI
            Path: /jwt-verification
            Method: POST

  DCSResponseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "dcs-response-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "resourceId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "resourceId"
          KeyType: "HASH"

  CRIPassportAuthCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cri-passport-auth-codes-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "authCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "authCode"
          KeyType: "HASH"

  CRIPassportAccessTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "cri-passport-access-tokens-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "accessToken"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "accessToken"
          KeyType: "HASH"

Outputs:
  IPVCriUkPassportAPIGatewayID:
    Description: CRI UK Passport API Gateway ID
    Export:
      Name: !Sub "${AWS::StackName}-IPVCriUkPassportAPIGatewayID"
    Value: !Ref IPVCriUKPassportAPI
