name: Test, Build, Package & Ship Passport Back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Set up SAM cli
        uses: aws-actions/setup-sam@v1

      - name: Set up AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Integration tests
        env:
          DCS_RESPONSE_TABLE_NAME: dcs-response-build
          JAR_ENCRYPTION_KEY_ID_PARAM: 180539d5-50e0-4984-8000-3aceadc942be
          JAR_KMS_PUBLIC_KEY_PARAM: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugDcZBuOLGOMbZbmDndZjP0JGGZzsCleOoo2/X8ahXZfFYZ2u1zotnYqQE5QI1BfDNOivw2jYaUcxgudPsqPj8uBfgunA/hnjZ9T5A20g9uRrX0aW5vk629ZU2u2hp64cCkDzrsbq3Iz74STSSA9ZN2HHO+L9qZmNzMp/Vg1jJwGpDsJXxARoCf2GBU8cWy3f1upvcgFR23OVXJO7+ou/9KFSUr7ksagwvrq880wNa7dvbPyQzwZBCuCoGyK2IhkovMeSJPomjKkzC8yS7hA0bai+V/9TiFa68T9nF/oucJIb2CRPvYmI2iScrq4FparBfn2sZH9LBz4EAyvB3TuvQIDAQAB
        run: ./gradlew intTest

      - name: SAM validate
        working-directory: ./deploy
        run: sam validate

      - name: SAM build and test
        working-directory: ./deploy
        run: sam build

      - name: Upload lambdas to S3
        working-directory: ./deploy
        env:
          ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
        run: sam package --s3-bucket="$ARTIFACT_BUCKET" --s3-prefix "passport" --output-template-file=cf-template.yaml

      - name: Zip the cloudformation template
        working-directory: ./deploy
        run: zip template.zip cf-template.yaml

      - name: Upload zipped cloudformation artifact to S3
        working-directory: ./deploy
        env:
          ARTIFACT_BUCKET: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
        run: aws s3 cp template.zip "s3://$ARTIFACT_BUCKET/passport/template.zip"
