name: Pre-merge integration test
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  deploy:
    name: pre-merge-integration-tests
    runs-on: ubuntu-latest
    environment: di-ipv-cri-dev
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
      STACK_NAME_PREFIX: pre-merge-integration
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: zulu

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Setup SAM
        uses: aws-actions/setup-sam@v1

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_PASSPORT_DEV_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SAM build
        run: sam build -t deploy/template.yaml

      - name: Set short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: SAM deploy integration test stack
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}

          sam deploy \
            --no-fail-on-empty-changeset \
            --no-confirm-changeset \
            --parameter-overrides "Environment=${{ env.ENVIRONMENT }} CodeSigningEnabled=false VpcStackName=none" \
            --stack-name $STACK_NAME \
            --s3-bucket ${{ secrets.AWS_PASSPORT_DEV_CONFIG_BUCKET }} \
            --s3-prefix $STACK_NAME \
            --region ${{ env.AWS_REGION }} \
            --capabilities CAPABILITY_IAM

      - name: Run API integration tests
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          BROWSER: chrome-headless
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
        run: |
          echo "🤞 now run integration tests..."
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          API_GATEWAY_ID_PRIVATE=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "IPVCriUkPassportPrivateAPIGatewayID").OutputValue')
          API_GATEWAY_ID_PUBLIC=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "IPVCriUkPassportBackAPIGatewayID").OutputValue')
          API_GATEWAY_KEY_ID=$(aws cloudformation describe-stacks --stack-name $STACK_NAME | jq -r '.Stacks[].Outputs[] | select(.OutputKey == "IpvCoreBackApiKeyId").OutputValue')
          API_GATEWAY_KEY=$(aws apigateway get-api-key --api-key $API_GATEWAY_KEY_ID --include-value | jq '.value' | tr -d '"')
          export API_GATEWAY_ID_PRIVATE=$API_GATEWAY_ID_PRIVATE
          export API_GATEWAY_ID_PUBLIC=$API_GATEWAY_ID_PUBLIC
          export API_GATEWAY_KEY=$API_GATEWAY_KEY
          cd acceptance-tests && ./gradlew clean cucumber -P tags=@pre-merge

      - name: Delete integration test stack
        if: always()
        run: |
          STACK_NAME=${{ env.STACK_NAME_PREFIX }}-${{ steps.vars.outputs.sha_short }}
          aws cloudformation delete-stack --region ${{ env.AWS_REGION }} --stack-name $STACK_NAME